### Lấy tất cả slot
GET http://localhost:8080/api/v1/slots
Accept: application/json

###

### Lấy các slot available
GET http://localhost:8080/api/v1/slots/available
Accept: application/json

###

### Đặt lịch vào slot có id = 1
POST http://localhost:8080/api/v1/slots/1/bookings
Content-Type: application/json

{
  "customerName": "Long",
  "customerEmail": "long@gmail.com"
}

###

### Đặt lịch vào slot có id = 2
POST http://localhost:8080/api/v1/slots/2/bookings
Content-Type: application/json

{
  "customerName": "Nguyen Van A",
  "customerEmail": "a@gmail.com"
}

### Create Slot 1

POST http://localhost:8080/api/v1/slots
Content-Type: application/json

{
  "slotDate": "2026-06-10",
  "startTime": "08:00:00",
  "endTime": "09:00:00",
  "status": "AVAILABLE"
}

###

### Create Slot 2

POST http://localhost:8080/api/v1/slots
Content-Type: application/json

{
  "slotDate": "2026-06-10",
  "startTime": "09:00:00",
  "endTime": "10:00:00",
  "status": "AVAILABLE"
}

###

### Create Slot 3

POST http://localhost:8080/api/v1/slots
Content-Type: application/json

{
  "slotDate": "2026-06-11",
  "startTime": "13:00:00",
  "endTime": "14:00:00",
  "status": "AVAILABLE"
}

###

### Get All Slots

GET http://localhost:8080/api/v1/slots
Accept: application/json

###

### Get Available Slots

GET http://localhost:8080/api/v1/slots/available
Accept: application/json

###

### Get Slot By Id

GET http://localhost:8080/api/v1/slots/1
Accept: application/json

###

### Delete Slot

DELETE http://localhost:8080/api/v1/slots/1
Accept: application/json
