### 1: ĐĂNG KÝ
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "dev",
  "password": "112233",
  "fullName": "Lập Trình Viên Chính"
}

### 2: ĐĂNG NHẬP
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "dev",
  "password": "112233"
}
