spring.application.name=booking-service
# Cấu hình kết nối cơ sở dữ liệu PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Cấu hình chuỗi bí mật mã hóa JWT (Tối thiểu 64 ký tự để tránh lỗi thuật toán HS512)
jwt.secret=9a4f2c8d3e1b7f6a5c4d3e2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f10987654321fedcbaabcdef0123456789